export const coffees = [
  {
    id: 1,
    name: "French",
    roast: "dark",
    src: "./img/coffees/french.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 2,
    name: "Verona",
    roast: "dark",
    src: "./img/coffees/verona.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 3,
    name: "Sumatra",
    roast: "dark",
    src: "./img/coffees/sumatra.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 4,
    name: "Vanilla",
    roast: "flavored",
    src: "./img/coffees/vanilla.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 5,
    name: "Breakfast Blend",
    roast: "medium",
    src: "./img/coffees/breakfast-brand.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 6,
    name: "Caramel",
    roast: "favored",
    src: "./img/coffees/caramel.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 7,
    name: "Cinnamon Dolce",
    roast: "favored",
    src: "./img/coffees/cinnamon-dolce.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 8,
    name: "Italian",
    roast: "dark",
    src: "./img/coffees/italian.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 9,
    name: "Espresso",
    roast: "dark",
    src: "./img/coffees/expresso.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 10,
    name: "House Blend",
    roast: "medium",
    src: "./img/coffees/house-blend.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 11,
    name: "Colombia",
    roast: "medium",
    src: "./img/coffees/colombia.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 12,
    name: "Maple Peacan",
    roast: "flavored",
    src: "./img/coffees/maple-peacan.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 13,
    name: "Morning Joe",
    roast: "dark",
    src: "./img/coffees/morning-joe.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 14,
    name: "Mocha",
    roast: "flavored",
    src: "./img/coffees/mocha.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
  {
    id: 15,
    name: "Pike Place",
    roast: "medium",
    src: "./img/coffees/pike-place.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
    price: 10.0,
  },
];
