export const coffees = [
  {
    id: 1,
    name: "French",
    roast: "dark",
    src: "./img/coffees/french.jpg",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 2,
    name: "Verona",
    roast: "dark",
    src: "../img/coffees/ ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 3,
    name: "Sumatra",
    roast: "dark",
    src: "../img/coffees/ ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 4,
    name: "Vanilla",
    roast: "flavored",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 5,
    name: "Breakfast Blend",
    roast: "medium",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 6,
    name: "Caramel",
    roast: "favored",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 7,
    name: "Cinamon Dolce",
    roast: "favored",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 8,
    name: "Italian",
    roast: "dark",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 9,
    name: "Espresso",
    roast: "dark",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 10,
    name: "House Blend",
    roast: "medium",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 11,
    name: "Colombia",
    roast: "medium",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 12,
    name: "Maple Peachan",
    roast: "flavored",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 13,
    name: "Morning Joe",
    roast: "dark",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 14,
    name: "Mocha",
    roast: "flavored",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 15,
    name: "Pike Place",
    roast: "medium",
    src: " ",
    desc: "lorem dolor sit amet, consectetur adipiscing elit",
  },
];
